extends: eslint-config-dmitmel
env:
  browser: true
  jest: true
rules:
  import/prefer-default-export: off
  import/no-extraneous-dependencies:
  - error
  - devDependencies:
    - scripts/*.js
    - config/**/*.js
    - src/**/*.test.{js,jsx}
settings:
  react:
    version: 16.2.0
