extends:
  - airbnb
  - plugin:prettier/recommended
  - prettier/react
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    generators: true
env:
  browser: true
  commonjs: true
  jest: true
rules:
  arrow-parens: off
  comma-dangle:
    - error
    - never
  curly:
    - error
    - multi-or-nest
    - consistent
  func-names: off
  function-paren-newline: off
  max-len: off
  no-param-reassign: off
  no-console: off
  no-mixed-operators: off
  no-multi-assign: off
  no-nested-ternary: off
  no-plusplus: off
  no-return-assign: off
  no-underscore-dangle: off
  no-unused-expressions:
    - error
    - allowShortCircuit: true
  no-use-before-define: off
  object-curly-newline: off
  prefer-destructuring:
    - error
    - VariableDeclarator:
        array: false
        object: true
      AssignmentExpression:
        array: false
        object: false
    - enforceForRenamedProperties: false
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - scripts/*.js
        - config/**/*.js
        - src/**/*.test.{js,jsx}
    - optionalDependencies: false
  react/forbid-prop-types: off
  react/no-array-index-key: off
  react/prop-types:
    - error
    - ignore:
        - children
      customValidators: []
      skipUndeclared: false
  react/require-default-props: off
settings:
  react:
    version: 16.2.0
