language: node_js
node_js: node

cache:
  yarn: true
  directories:
  - .eslintcache

install:
  - yarn install
script:
  - yarn lint --cache --cache-location ".eslintcache/"
  - yarn test --coverage

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
